'''
Created on Dec 15, 2017

@author: SperginPC
'''
"""
CS 229 Machine Learning, Fall 2017
Problem Set 4
Question: Reinforcement Learning: The inverted pendulum
Author: Sanyam Mehra, sanyam@stanford.edu
Adapted by: Nicholas Tan, Sean Fitzgerald, Erik Augustine
"""
from __future__ import division, print_function
import physics
import neural
import math
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import lfilter

"""
Parts of the code (cart and pole dynamics, and the state
discretization) are inspired from code available at the RL repository
http://www-anw.cs.umass.edu/rlr/domains.html
This file controls the pole-balancing simulation. You only need to
write code in between places marked
###### BEGIN YOUR CODE ######
###### END YOUR CODE ######
Briefly, the cart-pole system is described in `cart_pole.py`. The main
simulation loop in this file calls the `simulate()` function for
simulating the pole dynamics, `get_state()` for discretizing the
otherwise continuous state space in discrete states, and `show_cart()`
for display.
Some useful parameters are listed below:
`NUM_STATES`: Number of states in the discretized state space
You must assume that states are numbered 0 through `NUM_STATES` - 1. The
state numbered `NUM_STATES` - 1 (the last one) is a special state that
marks the state when the pole has been judged to have fallen (or when
the cart is out of bounds). However, you should NOT treat this state
any differently in your code. Any distinctions you need to make between
states should come automatically from your learning algorithm.
After each simulation cycle, you are supposed to update the transition
counts and rewards observed. However, you should not change either
your value function or the transition probability matrix at each
cycle.
Whenever the pole falls, a section of your code below will be
executed. At this point, you must use the transition counts and reward
observations that you have gathered to generate a new model for the MDP
(i.e. transition probabilities and state rewards). After that, you
must use value iteration to get the optimal value function for this MDP
model.
`TOLERANCE`: Controls the convergence criteria for each value iteration
run. In value iteration, you can assume convergence when the maximum
absolute change in the value function at any state in an iteration
becomes lower than `TOLERANCE.
You need to write code that chooses the best action according
to your current value function, and the current model of the MDP. The
action must be either 0 or 1 (corresponding to possible directions of
pushing the cart)
Finally, we assume that the simulation has converged when
`NO_LEARNING_THRESHOLD` consecutive value function computations all
converged within one value function iteration. Intuitively, it seems
like there will be little learning after this, so we end the simulation
here, and say the overall algorithm has converged.
Learning curves can be generated by calling a code snippet at the end
(it assumes that the learning was just executed, and the array
`time_steps_to_failure` that records the time for which the pole was
balanced before each failure are in memory). `num_failures` is a variable
that stores the number of failures (pole drops / cart out of bounds)
till now.
Other parameters in the code are described below:
`GAMMA`: Discount factor to be used
The following parameters control the simulation display; you dont
really need to know about them:
`pause_time`: Controls the pause between successive frames of the
display. Higher values make your simulation slower.
`min_trial_length_to_start_display`: Allows you to start the display only
after the pole has been successfully balanced for at least this many
trials. Setting this to zero starts the display immediately. Choosing a
reasonably high value (around 100) can allow you to rush through the
initial learning quickly, and start the display only after the
performance is reasonable.
"""


# Simulation parameters
pause_time = 0.0001
min_trial_length_to_start_display = 10000000
display_started = min_trial_length_to_start_display == 0


NUM_ACTIONS = 5
GAMMA = 0.995
TOLERANCE = 0.01
NO_LEARNING_THRESHOLD = 200

# Time cycle of the simulation
time = 0

# These variables perform bookkeeping (how many cycles was the pole
# balanced for before it fell). Useful for plotting learning curves.
time_steps_to_failure = []
num_failures = 0
time_at_start_of_current_trial = 0

# You should reach convergence well before this
max_failures = 400

# Initialize a cart pole
nn = neural.net()
nn.load_params('trained7.npz')
p = physics.pendulum()
p.reset()

nn_states = []
states = []

use_p = False
use_nn = False
if use_nn:
    state = p.get_state_img(nn)
else:
    state = p.get_state()


NUM_STATES = p.num_states

# Perform all your initializations here:
# Assume no transitions or rewards have been observed.
# Initialize the value function array to small random values (0 to 0.10,
# say).
# Initialize the transition probabilities uniformly (ie, probability of
# transitioning for state x to state y using action a is exactly
# 1/NUM_STATES).
# Initialize all state rewards to zero.

###### BEGIN YOUR CODE ######

#  Initialize value function to small random values
V = np.random.uniform(0,0.1,(NUM_STATES,1))
#  Initialize transition probabilities uniformly P[state,action]
# P_sa = np.random.uniform(0,1,(NUM_STATES, NUM_ACTIONS, NUM_STATES))
P_sa = np.full((NUM_STATES, NUM_ACTIONS, NUM_STATES), 1 / float(NUM_STATES))
#  Initialize all state rewards to zero.
Rewards = np.zeros((NUM_STATES, 1))
#  Initialize the model to zero counts of (state, action, new_state)
model_probabilities = np.zeros((NUM_STATES, NUM_ACTIONS, NUM_STATES))
model_rewards = np.zeros((NUM_STATES,2))

###### END YOUR CODE ######

# This is the criterion to end the simulation.
# You should change it to terminate when the previous
# 'NO_LEARNING_THRESHOLD' consecutive value function computations all
# converged within one value function iteration. Intuitively, it seems
# like there will be little learning after this, so end the simulation
# here, and say the overall algorithm has converged.

mean_error_i = []
mean_error = []
while num_failures < max_failures:
# consecutive_no_learning_trials = 0
# while consecutive_no_learning_trials < NO_LEARNING_THRESHOLD:

    # Write code to choose action (0 or 1).
    # This action choice algorithm is just for illustration. It may
    # convince you that reinforcement learning is nice for control
    # problems!  Replace it with your code to choose an action that is
    # optimal according to the current value function, and the current MDP
    # model.
    ###### BEGIN YOUR CODE ######

    # ONLY WORKS WHEN ACTION SPACE ONLY HAS TWO OPTIONS
    # min_action = np.argmin(P_sa[state] @ V)
    if use_p:
        step_size = 2*abs(math.pi-p.theta_lim)/5
        action = 4 - int((p.theta[1] - p.theta_lim) / step_size)
    else:
        action = np.argmax(P_sa[state] @ V)
    # if min_action == action:
    #     action = np.random.randint(0,1)

    if time % 1000 == 0:
        # print("xxxxxxxxxxxxxxxxxxxx")
        # print(time)
        # print("xxxxxxxxxxxxxxxxxxxx")
        action = np.random.randint(0,4)

    ###### END YOUR CODE ######

    # Get the next state by simulating the dynamics
    torque = 1*(action-2)
    # torque = -10*(p.theta[1] - math.pi) # classical control with infinite action space
    p.update([torque, 0])

    # Increment simulation time
    time = time + 1

    # Get the state number corresponding to new state vector
    if use_nn:
        new_state = p.get_state_img(nn)
        R = -abs(math.pi - p.theta_nn)
    else:
        new_state = p.get_state()
        # reward function to use - do not change this!
        R = -abs(math.pi - p.theta[1])
        # if new_state == NUM_STATES - 1:
        #     R = -1
        # else:
        #     R = 0

    mean_error_i.append(-R)

    # Perform model updates here.
    # A transition from `state` to `new_state` has just been made using
    # `action`. The reward observed in `new_state` (note) is `R`.
    # Write code to update your statistics about the MDP i.e. the
    # information you are storing on the transitions and on the rewards
    # observed. Do not change the actual MDP parameters, except when the
    # pole falls (the next if block)!

    ###### BEGIN YOUR CODE ######

    # record the number of times `state, action, new_state` occurs
    model_probabilities[state][action][new_state] += 1
    # record the rewards for every `new_state`
    model_rewards[new_state][0] += R
    # record the number of times `new_state` was reached
    model_rewards[new_state][1] += 1

    ###### END YOUR CODE ######

    # Recompute MDP model whenever pole falls
    # Compute the value function V for the new model
    time_up = time - time_at_start_of_current_trial
    if new_state == NUM_STATES - 1 or time_up > 50000:

        # Update MDP model using the current accumulated statistics about the
        # MDP - transitions and rewards.
        # Make sure you account for the case when a state-action pair has never
        # been tried before, or the state has never been visited before. In that
        # case, you must not change that component (and thus keep it at the
        # initialized uniform distribution).

        ###### BEGIN YOUR CODE ######

        total_actions_taken = np.sum(model_probabilities, keepdims = True, axis = 2)
        np.divide(model_probabilities, total_actions_taken,\
                out = P_sa, where = total_actions_taken != 0)
        total_rewardable_states = model_rewards[:,1].reshape((NUM_STATES,1))
        np.divide(model_rewards[:,0].reshape((NUM_STATES,1)), total_rewardable_states,\
                out = Rewards, where = total_rewardable_states!=0)

        ###### END YOUR CODE ######

        # Perform value iteration using the new estimated model for the MDP.
        # The convergence criterion should be based on `TOLERANCE` as described
        # at the top of the file.
        # If it converges within one iteration, you may want to update your
        # variable that checks when the whole simulation must end.

        ###### BEGIN YOUR CODE ######

        #  Compare this with the old V(s)
        diffs = TOLERANCE + 1
        num_iterations = 0
        while diffs > TOLERANCE:
            #  Start another iteration
            V_new = Rewards + np.amax(GAMMA * (P_sa @ V), axis=1)
            diffs = np.max(np.abs(V_new - V))
            V = V_new
            #  increment the iteration counter
            num_iterations += 1
        V = V_new
        print(num_iterations)
        if num_iterations == 1:
            consecutive_no_learning_trials += 1
        else:
            consecutive_no_learning_trials = 0

        ###### END YOUR CODE ######

    # # Do NOT change this code: Controls the simulation, and handles the case
    # # when the pole fell and the state must be reinitialized.
    # if new_state == NUM_STATES - 1:
        num_failures += 1

        if num_failures == max_failures:
            p.plot_arm(1)

        if num_failures >= max_failures:
            break
        print(time - time_at_start_of_current_trial)
        print('[INFO] Failure number {}'.format(num_failures))
        time_steps_to_failure.append(time - time_at_start_of_current_trial)
        # time_steps_to_failure[num_failures] = time - time_at_start_of_current_trial
        time_at_start_of_current_trial = time

        mean_error.append(sum(mean_error_i)/len(mean_error_i))
        mean_error_i = []

        theta0 = (math.pi - np.random.uniform()*math.pi*2/180)*(np.random.randint(0,1)*2-1)
        theta0 = theta0 % (2*math.pi)

        p.reset(theta=[0,theta0])
        if use_nn:
            state = p.get_state_img(nn)
        else:
            state = p.get_state()

    else:
        state = new_state



# plot the learning curve (time balanced vs. trial)
# log_tstf = np.log(np.array(time_steps_to_failure))
# plt.plot(np.arange(len(time_steps_to_failure)), log_tstf, 'k')
plt.plot(np.arange(len(time_steps_to_failure)), time_steps_to_failure, 'k')
plt.plot()
window = 30
w = np.array([1/window for _ in range(window)])
# weights = lfilter(w, 1, log_tstf)
# x = np.arange(window//2, len(log_tstf) - window//2)
# plt.plot(x, weights[window:len(log_tstf)], 'r--')
weights = lfilter(w, 1, time_steps_to_failure)
x = np.arange(window//2, len(time_steps_to_failure) - window//2)
plt.plot(x, weights[window:len(time_steps_to_failure)], 'r--')
plt.xlabel('Num failures')
plt.ylabel('Num steps to failure')
plt.yscale('log')
plt.show()

plt.plot(np.arange(len(mean_error)), mean_error)
plt.show()

print('mean error: ' + str(sum(mean_error[200:]) / (len(mean_error)-200+1)))
print('accuracy: ' + str(sum(time_steps_to_failure[200:])/(len(time_steps_to_failure)-200+1)))
